title="ISEAL Core Metadata Set"
baseURL="https://alanorth.github.io/iseal-schema"
languageCode = "en-us"
enableRobotsTXT = true
publishDir = "docs"
disablePathToLower = true

[permalinks]
  terms = "/:slug/"

[params]
  # Site author
  author = "Alan Orth"

  # Description/subtitle for homepage
  description = "Documenting metadata elements and controlled vocabularies for the ISEAL Core Metadata Set."
